services:

  postgres:
    image: 'postgres:18.3'
    container_name: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=jparelationshipsdb'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "jparelationshipsdb"]
      interval: 3s
      timeout: 3s
      retries: 5